name: "Publish to WebDAV"

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get npm cache directory
        shell: bash
        run: echo "NPM_CACHE_DIR=$(npm config get cache)" >> $GITHUB_ENV

      - name: Setup npm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.NPM_CACHE_DIR }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Upload to WebDAV
        uses: weijia/action-upload-webdav@master
        with:
          webdav-url: ${{ secrets.WEBDAV_URL }}
          webdav-username: ${{ secrets.WEBDAV_USERNAME }}
          webdav-password: ${{ secrets.WEBDAV_PASSWORD }}
          webdav-root: online/vue-bookmark-on-bolt
          source-directory: ./dist
